#include <string>

#include <wayland-client.h>
#include <xdg-shell-client-protocol.h> // generated by wayland-scanner

#include "coolgui/log.hpp"
#include "coolgui/platform/wayland_traits.hpp"
#include "coolgui/window_types.hpp"

namespace coolgui {

// ---------------------------------------------------------------------------
// xdg_wm_base listener — must respond to ping to keep the compositor happy
// ---------------------------------------------------------------------------
static void xdg_wm_base_ping(void * /*data*/, xdg_wm_base *base, u32 serial) { xdg_wm_base_pong(base, serial); }

static constexpr xdg_wm_base_listener k_xdg_wm_base_listener{
    .ping = xdg_wm_base_ping,
};

// ---------------------------------------------------------------------------
// xdg_surface listener — acknowledge configure events
// ---------------------------------------------------------------------------
static void xdg_surface_configure(void *data, xdg_surface *xdg_surf, u32 serial) {
  auto *state = static_cast<WaylandState *>(data);
  xdg_surface_ack_configure(xdg_surf, serial);
  state->configured = true;

  // Apply any pending resize
  if (state->resize_pending && state->surface != nullptr) {
    wl_surface_commit(state->surface);
    state->resize_pending = false;
  }
}

static constexpr xdg_surface_listener k_xdg_surface_listener{
    .configure = xdg_surface_configure,
};

// ---------------------------------------------------------------------------
// xdg_toplevel listener — handle close and configure (resize)
// ---------------------------------------------------------------------------
static void xdg_toplevel_configure(void *data, xdg_toplevel * /*toplevel*/, i32 width, i32 height,
                                   wl_array * /*states*/) {
  auto *state = static_cast<WaylandState *>(data);
  if (width > 0 && height > 0) {
    state->pending_width = static_cast<u32>(width);
    state->pending_height = static_cast<u32>(height);
    state->resize_pending = true;
  }
}

static void xdg_toplevel_close(void *data, xdg_toplevel * /*toplevel*/) {
  auto *state = static_cast<WaylandState *>(data);
  state->close_requested = true;
}

static constexpr xdg_toplevel_listener k_xdg_toplevel_listener{
    .configure = xdg_toplevel_configure,
    .close = xdg_toplevel_close,
};

// ---------------------------------------------------------------------------
// wl_registry listener — bind globals
// ---------------------------------------------------------------------------
static void registry_global(void *data, wl_registry *registry, u32 name, const char *interface, u32 version) {
  auto *state = static_cast<WaylandState *>(data);

  if (std::string_view{interface} == wl_compositor_interface.name) {
    state->compositor =
        static_cast<wl_compositor *>(wl_registry_bind(registry, name, &wl_compositor_interface, version));
  } else if (std::string_view{interface} == xdg_wm_base_interface.name) {
    state->xdg_wm = static_cast<xdg_wm_base *>(wl_registry_bind(registry, name, &xdg_wm_base_interface, version));
    xdg_wm_base_add_listener(state->xdg_wm, &k_xdg_wm_base_listener, nullptr);
  }
}

static void registry_global_remove(void * /*data*/, wl_registry * /*registry*/, u32 /*name*/) {
  // Not handled for now
}

static constexpr wl_registry_listener k_registry_listener{
    .global = registry_global,
    .global_remove = registry_global_remove,
};

// ---------------------------------------------------------------------------
// WaylandTraits implementation
// ---------------------------------------------------------------------------
auto WaylandTraits::create(WindowConfig cfg) -> Handle {
  auto state = std::make_unique<WaylandState>();

  state->display = wl_display_connect(nullptr);
  if (state->display == nullptr) {
    LOGE("Failed to connect to Wayland display");
    return Handle{};
  }

  state->registry = wl_display_get_registry(state->display);
  wl_registry_add_listener(state->registry, &k_registry_listener, state.get());
  wl_display_roundtrip(state->display); // populate compositor + xdg_wm_base

  if (state->compositor == nullptr || state->xdg_wm == nullptr) {
    LOGE("Wayland compositor or xdg_wm_base not available");
    wl_display_disconnect(state->display);
    return Handle{};
  }

  state->surface = wl_compositor_create_surface(state->compositor);
  state->xdg_surf = xdg_wm_base_get_xdg_surface(state->xdg_wm, state->surface);
  xdg_surface_add_listener(state->xdg_surf, &k_xdg_surface_listener, state.get());

  state->toplevel = xdg_surface_get_toplevel(state->xdg_surf);
  xdg_toplevel_add_listener(state->toplevel, &k_xdg_toplevel_listener, state.get());

  auto titleStr = std::string{cfg.title.get()};
  xdg_toplevel_set_title(state->toplevel, titleStr.c_str());

  xdg_toplevel_set_min_size(state->toplevel, static_cast<i32>(cfg.width.get()), static_cast<i32>(cfg.height.get()));

  wl_surface_commit(state->surface);
  wl_display_roundtrip(state->display); // wait for initial configure

  LOGI("Wayland window created: {}x{}", cfg.width.get(), cfg.height.get());
  return Handle{std::move(state)};
}

auto WaylandTraits::destroy(Handle &handle) -> void {
  if (handle.state == nullptr) {
    return;
  }
  WaylandState &s = *handle.state;

  if (s.toplevel != nullptr) {
    xdg_toplevel_destroy(s.toplevel);
    s.toplevel = nullptr;
  }
  if (s.xdg_surf != nullptr) {
    xdg_surface_destroy(s.xdg_surf);
    s.xdg_surf = nullptr;
  }
  if (s.surface != nullptr) {
    wl_surface_destroy(s.surface);
    s.surface = nullptr;
  }
  if (s.xdg_wm != nullptr) {
    xdg_wm_base_destroy(s.xdg_wm);
    s.xdg_wm = nullptr;
  }
  if (s.compositor != nullptr) {
    wl_compositor_destroy(s.compositor);
    s.compositor = nullptr;
  }
  if (s.registry != nullptr) {
    wl_registry_destroy(s.registry);
    s.registry = nullptr;
  }
  if (s.display != nullptr) {
    wl_display_disconnect(s.display);
    s.display = nullptr;
  }

  handle.state.reset();
  LOGI("Wayland window destroyed");
}

auto WaylandTraits::poll_event(Handle &handle) -> std::optional<Event> {
  if (handle.state == nullptr) {
    return std::nullopt;
  }
  WaylandState &s = *handle.state;

  // Dispatch pending events without blocking
  if (wl_display_dispatch_pending(s.display) < 0) {
    return Event{CloseEvent{}};
  }
  wl_display_flush(s.display);

  if (s.close_requested) {
    s.close_requested = false;
    return Event{CloseEvent{}};
  }

  if (s.resize_pending && s.configured) {
    ResizeEvent ev{.width = Width{s.pending_width}, .height = Height{s.pending_height}};
    s.resize_pending = false;
    s.pending_width = 0;
    s.pending_height = 0;
    return Event{ev};
  }

  return std::nullopt;
}

} // namespace coolgui
